info:
  app:
    version: @project.version@
spring:
  application:
    name: @project.artifactId@
  output:
    ansi:
      enabled: always
server:
  port: 8081
kafka:
  bootstrap:
    address: localhost
    port: 29092
  consumer:
    auto-offset-reset: earliest
    topic: topic
    group-id: myId