info:
  app:
    name: @project.artifactId@
    version: @project.version@
spring:
  output:
    ansi:
      enabled: always
server:
  port: 8081
kafka:
  bootstrap:
    address: localhost
    port: 9092 # for kafka on docker replace it with 29092
  consumer:
    auto-offset-reset: earliest
    topic: topic
    group-id: myId