info:
  app:
    version: @project.version@
spring:
  application:
    name: @project.artifactId@
  output:
    ansi:
      enabled: always
server:
  port: 8080
kafka:
  bootstrap:
    address: localhost
    port: 29092
  producer:
    topic: topic